<a href="https://colab.research.google.com/github/suyon0416/ESAA_YB_WEEK1/blob/main/YB_0904_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [2]:
import numpy as np

A = np.ones((5, 3))
B = np.ones((3, 2))
Z = np.dot(A, B)
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
import numpy as np

Z = np.arange(11)

# 3과 8 사이(3, 8 포함)의 요소를 음수로 변경
Z[(Z >= 3) & (Z <= 8)] *= -1

print(Z)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [6]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [4]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [5]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_4873/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_4873/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_4873/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [7]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# 두 배열의 공통 값(교집합) 찾기
common_values = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print("공통 값:", common_values)

Z1: [2 7 3 1 2 1 2 5 1 0]
Z2: [5 9 0 3 8 0 0 0 3 5]
공통 값: [0 3 5]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [8]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_4873/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

False. nan!=1j


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [9]:
# 2016년 7월 1일부터 2016년 8월 1일 직전(7월 31일)까지 하루 단위('D')로 생성
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [10]:
A = np.ones(3, dtype=np.float64) * 1
B = np.ones(3, dtype=np.float64) * 2

# 순서대로 out을 지정하여 메모리 할당 없이 계산
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [11]:
Z = np.random.uniform(0, 10, 10)

# 방법 1: % (모듈로 연산자 활용) - 전체 값에서 소수점 아래 버리기
method1 = Z - Z % 1

# 방법 2: // (정수 나눗셈 연산자 활용)
method2 = Z // 1

# 방법 3: np.floor() 함수 사용
method3 = np.floor(Z)

# 방법 4: astype(int) 형변환 사용
method4 = Z.astype(int)

# 방법 5: np.trunc() (소수점 자르기) 사용
method5 = np.trunc(Z)

print("원본:", Z)
print("정수부(방법1):", method1)
print("정수부(방법2):", method2)

원본: [4.39973834 3.75077406 2.23917557 8.59118178 9.15844244 6.1822214
 4.11614687 6.08794486 5.80641689 4.56464533]
정수부(방법1): [4. 3. 2. 8. 9. 6. 4. 6. 5. 4.]
정수부(방법2): [4. 3. 2. 8. 9. 6. 4. 6. 5. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [12]:
Z = np.zeros((5, 5)) + np.arange(5)

print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [13]:
Z = np.random.random(10)
Z.sort()

print(Z)

[0.18452751 0.2388805  0.28390757 0.51638193 0.65328603 0.76707224
 0.81118982 0.9206425  0.93421974 0.94502878]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [14]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

equal1 = np.array_equal(A, B)

print("A:", A)
print("B:", B)
print("두 배열이 일치하는가?:", equal1)

A: [1 1 1 1 1]
B: [0 0 0 1 0]
두 배열이 일치하는가?: False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [15]:
# 10x2 무작위 직교 좌표계 (x, y) 생성
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]

# 극좌표계로 변환 (거리 R, 각도 T)
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)

print("거리 (R):", R)
print("각도 (T):", T)

거리 (R): [0.82652288 0.55780528 0.97661836 0.67826231 0.51444052 0.99844245
 0.64955513 0.21634009 1.10322719 1.1008425 ]
각도 (T): [0.08414386 1.07321582 0.28564968 0.35960089 1.47054283 1.41871703
 0.21254826 0.83145814 0.54998859 0.67948901]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [16]:
Z = np.random.random(10)
print("변경 전 Z:", Z)

# 최댓값의 인덱스를 찾아 0으로 변경
Z[Z.argmax()] = 0

print("변경 후 Z:", Z)

변경 전 Z: [0.33343243 0.61532175 0.4264914  0.32272734 0.97522611 0.91576311
 0.01344685 0.24031033 0.7709907  0.56752512]
변경 후 Z: [0.33343243 0.61532175 0.4264914  0.32272734 0.         0.91576311
 0.01344685 0.24031033 0.7709907  0.56752512]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [17]:
Z = np.arange(100)
v = np.random.uniform(0, 100)

# 1. Z의 각 요소와 v 사이의 절대 거리(abs) 계산 후, 최소 거리가 있는 인덱스 찾기
index = np.abs(Z - v).argmin()

# 2. 해당 인덱스의 실제 값 출력
closest_value = Z[index]

print("기준 값 v:", v)
print("가장 가까운 값:", closest_value)

기준 값 v: 4.3064167546374215
가장 가까운 값: 4


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [18]:
import numpy as np

Z = np.arange(9).reshape(3, 3)

# 인덱스(index)와 값(x)을 동시에 순회
for index, x in np.ndenumerate(Z):
    print(index, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [19]:
n = 10  # 2차원 배열의 크기 (10x10)
p = 3   # 무작위로 배치할 요소의 개수

# 1. 10x10 크기의 0으로 채워진 배열 생성
Z = np.zeros((n, n))

# 2. 0부터 (n*n - 1)까지의 인덱스 중 p개를 중복 없이(replace=False) 무작위 선택하여 값(1)을 넣음
np.put(Z, np.random.choice(range(n * n), p, replace=False), 1)

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [20]:
Z = np.random.randint(0, 10, (3, 3))
print("정렬 전 Z:\n", Z)

n = 1  # 정렬 기준이 될 열의 인덱스 (0: 첫 번째 열, 1: 두 번째 열)

# n번째 열의 값을 기준으로 정렬된 행 인덱스를 구해서 배열 재배열
Z_sorted = Z[Z[:, n].argsort()]

print(f"\n{n}번째 열 기준 정렬 후 Z:\n", Z_sorted)

정렬 전 Z:
 [[2 3 7]
 [7 4 1]
 [4 2 4]]

1번째 열 기준 정렬 후 Z:
 [[4 2 4]
 [2 3 7]
 [7 4 1]]
